export interface EditorialVariation {
  id: string;
  companion: boolean;
  npc: string;
  location: string;
  quest: string;
  encounter: string;
  rumor: string;
  dungeon: string;
}

/**
 * Each variation is written for the field where it appears. This prevents a
 * generic sentence from becoming a misplaced hook, twist, clue, or room note.
 */
export const VARIATION_BEATS: readonly EditorialVariation[] = [
  {
    id: "testemunha",
    companion: false,
    npc: "Uma testemunha procura essa pessoa porque reconheceu seu nome em uma carta interceptada.",
    location: "Uma testemunha viu alguém alterar o marco local durante a madrugada e reconheceu o brasão preso ao manto.",
    quest: "Uma testemunha entrega a prova somente se o grupo retirar sua família da rota do perigo.",
    encounter: "A pessoa encurralada causou parte do problema e admite o erro se receber proteção.",
    rumor: "A única testemunha muda pequenos detalhes a cada relato, mas nunca altera o horário em que tudo aconteceu.",
    dungeon: "Pegadas recentes mostram que outro grupo entrou há poucas horas e ainda pode estar nas salas adiante.",
  },
  {
    id: "vestigio",
    companion: true,
    npc: "Um vestígio encontrado em seu equipamento contradiz a versão pública de sua última viagem.",
    location: "Cinzas ainda mornas revelam que o lugar foi usado depois do suposto abandono.",
    quest: "Um vestígio no caminho prova que a oposição conhece a rota planejada e prepara uma emboscada.",
    encounter: "Os sinais de violência foram encenados para esconder uma fuga combinada entre dois adversários.",
    rumor: "Um objeto deixado no local confirma a parte mais improvável da história, mas aponta para outro responsável.",
    dungeon: "Restos de comida, cera fresca e uma corda cortada revelam que as salas não estão abandonadas.",
  },
  {
    id: "acordo",
    companion: false,
    npc: "Um acordo antigo lhe dá autoridade para negociar, embora a outra parte prefira fingir que o documento não existe.",
    location: "Uma placa de pedra registra um acordo que ainda obriga as duas comunidades rivais.",
    quest: "O objetivo pode ser alcançado sem confronto se o grupo provar que um tratado esquecido continua válido.",
    encounter: "Os dois lados desejam cumprir o acordo, mas discordam sobre quem deve dar o primeiro passo.",
    rumor: "A história omite que o acontecimento foi previsto em um tratado guardado por ambas as partes.",
    dungeon: "Uma inscrição estabelece regras de passagem; cumpri-las abre uma rota que os invasores não perceberam.",
  },
  {
    id: "prazo",
    companion: true,
    npc: "Essa pessoa precisa agir antes do próximo amanhecer, quando a única testemunha deixará a região.",
    location: "Ao cair da noite, uma mudança no ambiente tornará o acesso perigoso por vários dias.",
    quest: "O prazo termina ao amanhecer, quando a prova perderá valor e a oposição assumirá o controle do local.",
    encounter: "A ameaça piora a cada poucos minutos, mas uma retirada apressada abandona pessoas inocentes.",
    rumor: "Quem espalha a história insiste que algo acontecerá ao amanhecer, e os sinais observáveis confirmam a urgência.",
    dungeon: "Água, fumaça ou areia avança pelas passagens; o grupo precisa decidir o que explorar antes que a rota se feche.",
  },
  {
    id: "aliado",
    companion: false,
    npc: "Um antigo aliado oferece ajuda, mas exige que sua participação permaneça em segredo.",
    location: "Uma moradora conhece um acesso seguro e aceita guiá-lo se o grupo proteger quem ficará para trás.",
    quest: "Um aliado hesitante conhece a fraqueza da oposição, mas teme ser reconhecido durante a operação.",
    encounter: "Uma pessoa do lado adversário tenta impedir a violência sem revelar que está traindo seus companheiros.",
    rumor: "A fonte mais bem informada trabalha para quem deseja abafar o caso e precisa falar sem ser descoberta.",
    dungeon: "Um habitante acuado conhece atalhos e hábitos dos ocupantes, mas não seguirá adiante sem garantias.",
  },
  {
    id: "objeto",
    companion: true,
    npc: "Um objeto comum que ela carrega contém a prova de uma acusação antiga.",
    location: "Uma peça de uso cotidiano esconde um mapa incompleto quando observada contra a luz.",
    quest: "A prova procurada está escondida em um objeto banal que já passou pelas mãos do contratante.",
    encounter: "O item disputado não tem valor material; sua importância está na mensagem gravada sob o revestimento.",
    rumor: "A história nasceu por causa de um objeto real, embora quase todos descrevam sua aparência de forma errada.",
    dungeon: "Um utensílio abandonado funciona como chave para um mecanismo que parece fazer parte da parede.",
  },
  {
    id: "rota",
    companion: false,
    npc: "Ela conhece uma rota que evita o perigo, mas atravessa terras de alguém que não esqueceu uma dívida.",
    location: "Um caminho secundário surge apenas quando o terreno, a maré ou o movimento das pessoas muda.",
    quest: "A rota mais segura exige um desvio pelo território de uma terceira parte que pode cobrar passagem.",
    encounter: "Há duas saídas visíveis: uma é rápida e exposta; a outra é lenta e passa perto da origem do problema.",
    rumor: "Todas as versões apontam para a rota principal, mas as marcas no terreno indicam outro caminho.",
    dungeon: "Uma passagem estreita contorna o obstáculo central e permite chegar ao outro lado sem enfrentá-lo de frente.",
  },
  {
    id: "promessa",
    companion: true,
    npc: "Uma promessa feita em público limita suas escolhas e oferece aos rivais uma forma de pressioná-la.",
    location: "Os moradores aguardam o cumprimento de uma promessa feita diante do marco central.",
    quest: "O contratante prometeu poupar a oposição, e quebrar sua palavra transformará aliados em inimigos.",
    encounter: "Uma das partes não pode recuar sem violar uma promessa conhecida por todos os presentes.",
    rumor: "A versão popular exagera o perigo para testar se uma promessa antiga ainda será cumprida.",
    dungeon: "A abertura de uma porta sela outra passagem, como advertia uma promessa inscrita na entrada.",
  },
  {
    id: "sinal",
    companion: false,
    npc: "Ela reconhece um sinal repetido nas últimas ocorrências e teme contar onde o viu pela primeira vez.",
    location: "O mesmo símbolo aparece em três pontos do lugar, sempre voltado para uma saída diferente.",
    quest: "Um sinal recorrente permite prever o próximo movimento da oposição, desde que seja interpretado a tempo.",
    encounter: "A ameaça reage a um som, uma cor ou um gesto que os presentes repetem sem perceber.",
    rumor: "O detalhe repetido em todos os relatos é verdadeiro e funciona como aviso para quem souber reconhecê-lo.",
    dungeon: "Marcas discretas indicam quais superfícies foram tocadas com segurança pelos ocupantes anteriores.",
  },
  {
    id: "preco",
    companion: true,
    npc: "Ela oferece exatamente a ajuda necessária, mas cobra um compromisso que produzirá consequências depois.",
    location: "O recurso mais útil do lugar pode ser tomado agora, embora sua retirada prejudique quem depende dele.",
    quest: "A solução mais rápida exige sacrificar a recompensa ou transferir o risco para pessoas inocentes.",
    encounter: "É possível encerrar o conflito imediatamente, desde que alguém aceite uma perda pública e irreversível.",
    rumor: "A história é verdadeira, mas quem a espalha esconde o preço cobrado de todos que tentaram agir.",
    dungeon: "O mecanismo central concede passagem em troca de um objeto valioso, uma lembrança ou uma promessa registrada.",
  },
  {
    id: "mensagem",
    companion: false,
    npc: "Uma mensagem incompleta pede sua presença e termina antes de revelar quem corre perigo.",
    location: "Uma frase interrompida foi gravada às pressas em um ponto visível apenas para quem está saindo.",
    quest: "A última mensagem do contato indica o destino correto, mas omite deliberadamente o nome de um cúmplice.",
    encounter: "Uma mensagem entregue durante o impasse prova que nenhum dos lados conhece toda a situação.",
    rumor: "O boato começou como uma mensagem truncada; recuperar o trecho ausente muda o sentido do aviso.",
    dungeon: "Uma sequência de inscrições forma uma mensagem quando as salas são percorridas na ordem correta.",
  },
  {
    id: "silencio",
    companion: true,
    npc: "Seu silêncio protege uma pessoa culpada de um erro menor, não do crime que todos imaginam.",
    location: "A pessoa que mais conhece o lugar se recusa a falar diante dos demais, mas deixa pistas intencionais.",
    quest: "O contratante omite um nome porque teme perder o apoio da comunidade antes do fim da missão.",
    encounter: "Todos acusam quem fala demais, enquanto a pessoa silenciosa controla a única saída.",
    rumor: "A ausência de um nome nos relatos é deliberada e revela quem exerce poder sobre as testemunhas.",
    dungeon: "Sinos quebrados e placas abafadas mostram que os antigos ocupantes precisavam atravessar algumas salas em silêncio.",
  },
  {
    id: "marca",
    companion: false,
    npc: "Uma marca recente em sua roupa pertence a uma organização que ela afirma nunca ter encontrado.",
    location: "Uma marca antiga recebeu um traço novo, gravado com ferramenta ainda coberta de pó.",
    quest: "O grupo precisa identificar quem alterou a marca de fronteira antes que duas comunidades se acusem.",
    encounter: "Os adversários usam a mesma marca, mas cada lado acredita que o outro a falsificou.",
    rumor: "A marca citada no boato existe, porém foi acrescentada recentemente para orientar alguém até o local.",
    dungeon: "Símbolos nas soleiras se repetem com pequenas diferenças e antecipam o perigo de cada sala.",
  },
  {
    id: "disputa",
    companion: true,
    npc: "Duas pessoas sinceras contam versões incompatíveis sobre uma decisão que ela tomou.",
    location: "Duas comunidades reivindicam o mesmo espaço e apresentam documentos igualmente convincentes.",
    quest: "Cumprir o pedido como foi formulado favorece uma das partes antes que o grupo conheça a versão rival.",
    encounter: "Os dois lados têm razões legítimas para permanecer, e nenhum deles iniciou a ameaça imediata.",
    rumor: "Duas versões contraditórias são verdadeiras em partes diferentes e revelam interesses opostos.",
    dungeon: "Dois grupos ocupam setores distintos e disputam um recurso que nenhum deles consegue alcançar sozinho.",
  },
  {
    id: "refugio",
    companion: false,
    npc: "Ela oferece um refúgio seguro por uma noite, mas a presença do grupo colocará seus moradores em risco.",
    location: "Um abrigo discreto permite observar o perigo e conversar com quem não pode aparecer em público.",
    quest: "O único ponto seguro abriga pessoas procuradas que não têm relação com o objetivo da missão.",
    encounter: "Uma área protegida comporta apenas parte dos presentes, e a ameaça já percebeu onde ela fica.",
    rumor: "A história aponta para um refúgio real, mas omite quem o mantém e por que sua localização é perigosa.",
    dungeon: "Uma sala defensável oferece descanso e visão das passagens, embora sinais recentes indiquem que alguém conhece o esconderijo.",
  },
  {
    id: "heranca",
    companion: true,
    npc: "Uma herança esquecida lhe dá direito sobre o objeto da disputa e responsabilidade pelas dívidas ligadas a ele.",
    location: "O lugar pertence legalmente a alguém que desconhece a própria herança.",
    quest: "A prova procurada revela um herdeiro legítimo, o que torna a entrega mais perigosa que a busca.",
    encounter: "A pessoa tratada como invasora possui o único documento capaz de comprovar sua ligação com o local.",
    rumor: "A história preservou o nome errado durante gerações, mas acertou a linhagem responsável pelo acontecimento.",
    dungeon: "Um selo de família abre depósitos e também desperta defesas criadas para testar futuros herdeiros.",
  },
  {
    id: "ritual",
    companion: false,
    npc: "Ela sabe executar um ritual capaz de conter a ameaça uma única vez e procura quem possa concluir o trabalho.",
    location: "Um ritual simples estabiliza o lugar até o próximo ciclo, mas exige a participação de grupos rivais.",
    quest: "O objetivo pode ser adiado por um ritual de contenção, dando tempo para encontrar uma solução permanente.",
    encounter: "Uma das partes tenta completar um ritual imperfeito enquanto a outra interpreta o ato como ataque.",
    rumor: "Os gestos descritos no boato pertencem a um ritual de proteção, não à invocação que todos temem.",
    dungeon: "Objetos distribuídos entre várias salas formam um ritual interrompido que pode ser concluído ou desfeito.",
  },
  {
    id: "devedor",
    companion: true,
    npc: "Uma pessoa endividada oferece acesso privilegiado em troca do perdão de uma obrigação legítima.",
    location: "O responsável pela manutenção do lugar desviou recursos para pagar uma dívida e agora tenta reparar o dano.",
    quest: "Um devedor conhece a rotina da oposição e ajuda o grupo se sua participação não for usada contra sua família.",
    encounter: "A pessoa que iniciou o impasse pretendia apenas cobrar uma dívida, mas perdeu o controle da situação.",
    rumor: "Quem espalhou a história tenta pressionar um devedor e acrescentou detalhes para expô-lo publicamente.",
    dungeon: "Registros guardados numa sala lateral mostram quem financiou a construção e qual dívida ainda pode ser cobrada.",
  },
  {
    id: "memoria",
    companion: false,
    npc: "Uma lembrança compartilhada com a pessoa errada explica sua lealdade e a origem de sua culpa.",
    location: "Os habitantes recordam o mesmo acontecimento de maneiras diferentes, mas todos mencionam um som específico.",
    quest: "Uma memória considerada irrelevante contém a ordem correta dos fatos e inocenta um suspeito conveniente.",
    encounter: "Um dos envolvidos reconhece o lugar e percebe que a ameaça repete um desastre do passado.",
    rumor: "A história mudou a cada geração, embora uma imagem concreta tenha permanecido intacta em todas as versões.",
    dungeon: "Murais danificados registram a rotina dos antigos ocupantes e revelam como eles evitavam os próprios mecanismos.",
  },
  {
    id: "escolha",
    companion: true,
    npc: "Ela pede que o grupo escolha quem receberá a informação primeiro e promete respeitar a decisão.",
    location: "Duas necessidades urgentes competem pelo mesmo recurso, e atender uma delas torna a outra mais difícil.",
    quest: "A missão termina com uma escolha entre entregar a prova, destruí-la ou torná-la pública.",
    encounter: "O grupo pode salvar quem está em perigo, capturar o responsável ou impedir a próxima ameaça, mas não fazer tudo ao mesmo tempo.",
    rumor: "Confirmar a história permite agir cedo; divulgá-la, porém, provoca a reação imediata dos interessados.",
    dungeon: "A última passagem obriga o grupo a escolher entre uma saída segura e o acesso ao que veio procurar.",
  },
];
